import os
import uuid
import json
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://"
)

client = Groq(api_key=os.getenv("GROQ_API_KEY"))
LOG_FILE = "audit_log.json"


# ── Signal 1: Groq LLM ──────────────────────────────────────────
def classify_with_groq(text):
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by AI.

Analyze the following text and rate how likely it is to be AI-generated.

Respond with ONLY a single number between 0 and 1:
- 0.0 means definitely human-written
- 1.0 means definitely AI-generated
- 0.5 means uncertain

Text to analyze:
\"\"\"{text}\"\"\"

Respond with only the number, nothing else."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=10,
        temperature=0.1
    )

    raw = response.choices[0].message.content.strip()
    score = float(raw)
    return max(0.0, min(1.0, score))


# ── Signal 2: Stylometrics ──────────────────────────────────────
def stylometric_score(text):
    import re

    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = re.findall(r'\b\w+\b', text.lower())

    if len(sentences) < 2 or len(words) < 10:
        return 0.5

    # Metric 1: sentence length variance
    # AI text is uniform → low variance → high AI score
    lengths = [len(re.findall(r'\b\w+\b', s)) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    # Normalize: variance > 50 = very human-like, cap at 50
    variance_score = 1.0 - min(variance / 50.0, 1.0)  # high variance → low AI score

    # Metric 2: type-token ratio (vocabulary diversity)
    # AI text reuses words less but in predictable patterns
    # Low TTR = repetitive = more AI-like
    ttr = len(set(words)) / len(words)
    # TTR < 0.6 = repetitive, > 0.85 = very diverse (human)
    ttr_score = 1.0 - min(max((ttr - 0.4) / 0.5, 0.0), 1.0)  # high TTR → low AI score

    # Metric 3: punctuation density
    # AI text uses fewer casual punctuation marks (dashes, ellipses, etc.)
    casual_punct = len(re.findall(r'[,\-\(\)!?;:\'\"]', text))
    punct_density = casual_punct / len(text) if text else 0
    # Density < 0.02 = very sparse (AI-like), > 0.08 = very human
    punct_score = 1.0 - min(max((punct_density - 0.01) / 0.07, 0.0), 1.0)

    combined = (variance_score + ttr_score + punct_score) / 3
    return round(combined, 3)


# ── Confidence scoring ──────────────────────────────────────────
def combine_scores(llm_score, stylo_score):
    return round((0.6 * llm_score) + (0.4 * stylo_score), 3)


# ── Attribution label ───────────────────────────────────────────
def get_attribution(score):
    if score > 0.65:
        return "likely_ai"
    elif score < 0.35:
        return "likely_human"
    else:
        return "uncertain"


# ── Transparency label ──────────────────────────────────────────
def get_label(score):
    pct = int(score * 100)
    if score > 0.65:
        return f"Our system detected patterns strongly associated with AI-generated writing (confidence: {pct}%). This does not prevent posting — it gives readers context. If you wrote this yourself, you can appeal."
    elif score < 0.35:
        human_pct = int((1 - score) * 100)
        return f"This content shows strong signals of human authorship (confidence: {human_pct}%). No action needed."
    else:
        return f"Our system is not confident about the origin of this content (confidence: {pct}%). Detection is imperfect. If this label seems wrong, you can submit an appeal."


# ── Audit log ───────────────────────────────────────────────────
def log_entry(entry):
    entries = []
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, "r") as f:
            entries = json.load(f)
    entries.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def get_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)


# ── Routes ───────────────────────────────────────────────────────
@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    text = data.get("text", "")
    creator_id = data.get("creator_id", "")
    content_id = str(uuid.uuid4())

    llm_score = classify_with_groq(text)
    stylo_score = stylometric_score(text)
    confidence = combine_scores(llm_score, stylo_score)
    attribution = get_attribution(confidence)
    label = get_label(confidence)

    log_entry({
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified"
    })

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label
    })


@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()})

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    content_id = data.get("content_id", "")
    reasoning = data.get("creator_reasoning", "")

    if not content_id:
        return jsonify({"error": "content_id is required"}), 400

    entries = get_log()
    updated = False

    for entry in entries:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = reasoning
            entry["appeal_timestamp"] = datetime.now(timezone.utc).isoformat()
            updated = True
            break

    if not updated:
        return jsonify({"error": "content_id not found"}), 404

    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)

    return jsonify({
        "status": "received",
        "content_id": content_id,
        "message": "Your appeal has been logged for human review."
    })
if __name__ == "__main__":
    app.run(debug=True)